services:
  - type: web
    name: tutorxpert-backend
    env: python
    region: singapore  # ğŸŒ é€‰æœ€è¿‘åŒºåŸŸ
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    plan: free
    envVars:
      - key: DATABASE_URL
        value: postgresql://tutorxpert_database_user:TIs4hJtmfLDK4l7tGOmtjb2imOyd55B6@dpg-d0rgpfndiees73c16vqg-a.singapore-postgres.render.com:5432/tutorxpert_database
